version: "3.7"
services:
    pg:
        image: postgres:10-alpine
        environment:
            - POSTGRES_PASSWORD=dbpass
            - POSTGRES_DB=postgres
        ports:
            - "5432:5432"
        networks:
            - custom
    my_sanic_app:
        image: luchanos/my_sanic_app:1.0.0
        ports:
            - "3000:6000"
        networks:
            - custom
networks:
    custom:
        driver: bridge
